server:
  port: 8084

spring:
  application:
    name: notification-service
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  server:
    url: http://localhost:8080 # Trỏ về API Gateway