jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
  expiration: 86400000 # Thời gian sống của Token (vd: 1 ngày = 86400000 ms)
  refresh:
    expiration: 604800000 # Thời gian sống của Refresh Token (vd: 7 ngày = 604800000 ms)
