server:
  port: 8086

spring:
  application:
    name: moderation-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5437/moderation_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: moderation-service-group
      auto-offset-reset: earliest
  swagger-ui:
    path: /swagger-ui.html
    server:
      url: http://localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
  expiration: 86400000 # Thời gian sống của Token (vd: 1 ngày = 86400000 ms)
  refresh:
    expiration: 604800000 # Thời gian sống của Refresh Token (vd: 7 ngày = 604800000 ms)
