spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db # Đảm bảo bạn đã tạo DB này trong Postgres
    username: root     # Thay bằng user Postgres của bạn
    password: password # Thay bằng pass Postgres của bạn
  jpa:
    hibernate:
      ddl-auto: update # Tự động tạo bảng dựa trên Entity
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: khonggian2k0520@gmail.com
    password: aels tpaf bipc nuio
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Cấu hình tự tạo cho JWT
jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
  expiration: 86400000 # Thời gian sống của Token (vd: 1 ngày = 86400000 ms)
  refresh:
    expiration: 604800000 # Thời gian sống của Refresh Token (vd: 7 ngày = 604800000 ms)
