spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    mongodb:
      uri: ${MONGODB_URI}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

jwt:
  secret: ${JWT_SECRET}

app:
  internal:
    token: ${INTERNAL_API_TOKEN}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
